s390: Fix s390_irgen_VSTER
M3 == 4 is a reserved value and causes a specification exception.
However, disasm-test reports:

error: Spec. exc. not detected for E660 0000 400F   vster %v6,0,4

Now fixed.