VEX: Fix srcdir != builddir build
commit 370531396ad1 ("s390: Use objdump machinery to disassemble insns")
broke srcdir != builddir builds with:

../../../VEX/priv/objdump/s390-dis.c:26:10: fatal error: main_util.h: No such file or directory
   26 | #include "main_util.h"     // vex_strlen
      |          ^~~~~~~~~~~~~

This comes from including the "wrong" priv directory for main_util.h
in Makefile.vex.am. Fix this by adding -I$(srcdir)/priv. This was
always wrong but didn't cause issues till now because of the extra
objdump subdir.