none/tests/bug234814.c: sa_handler take an int as argument
GCC15 will turn this warning into an error:

bug234814.c: In function 'main':
bug234814.c:20:18: error: assignment to '__sighandler_t' {aka 'void (*)(int)'} from incompatible pointer type 'void (*)(void)' [-Wincompatible-pointer-types]
   20 |    sa.sa_handler = mysigbus;
      |                  ^

(cherry picked from commit 8f6cef269b91739f6a2e7f3b4b1e0a429db3e748)