s390: Fix s390_irgen_VMSL
The reserved bits in M3, when set, do not cause a specification exception.
However, disasm-test reports e.g:

error: Unexpected spec. exc. detected for E764 1310 92B8   vmslg %v6,%v4,%v17,%v9,1

Now fixed.